apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: ip-240-242
      protocol: layer2
      addresses:
      - 10.1.10.240-10.1.10.242
